spring:
  profiles:
    active: local
  application:
    name: order_manager
  doc:
    api:
      title: Order Manager API
      description: API documentation for Order Manager API which is used to manage orders.
      version: 1.0.0
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
