spring:
  datasource:
    url: jdbc:mysql://localhost:3305/order_db
    username: admire
    password: password

logging:
  level:
    org.hibernate.SQL: DEBUG
    springframework.validationDEBUG: DEBUG